version: '3'                    # Docker Composeファイルのバージョンを指定します。
services:                       # ここからサービスの定義を始めます。
  web:
    build: .
    command: npm run dev #本番時はnpm run start
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /web/src/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:                      # ポートマッピングを設定します。
      - "3000:3000"             # ホストのポート3000をコンテナのポート3000にマッピングします。
    env_file:
      - .env.local
