version: '3'                    # Docker Composeファイルのバージョンを指定します。
services:                       # ここからサービスの定義を始めます。
  web:
    build: .
    command: npm run dev #本番時はnpm run start
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /web/src/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:                      # ポートマッピングを設定します。
      - "3000:3000"             # ホストのポート3000をコンテナのポート3000にマッピングします。

    # volumes:
    #   - ./src/app:/src/web
    # volumes:
      # バインドボリューム
      # - .:/usr/src/app
      # 永続化ボリューム
      # - /usr/src/app/node_modules

    # command: npm run dev
    # command: npm run start:watch
    # environment: #本番運用時は削除する
    # - NODE_ENV=development #開発者モード
    # - CHOKIDAR_USEPOLLING=true